name: jupol_prueba
version: 1.0.0+1
publish_to: none
description: Jupol Prueba app.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  curved_navigation_bar: ^1.0.1

  table_calendar: ^3.0.3

  http: ^0.13.4
  flutter_html: ^2.1.5
  html_unescape: ^2.0.0
  shimmer: ^2.0.0


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

